### ISSUE TITLE
Supporting multiple sheets.

### ISSUE THREAD

**Issue by aryan00018** [yangxiaoge/AndroidExcelReadWrite#1]
Whether this support mutilple sheets or not? I am not able to view the multiple sheet present in the excel.

**Comment by yangxiaoge** [comment]
> Whether this support mutilple sheets or not? I am not able to view the multiple sheet present in the excel.

yes, you can edit [ExcelUtil.java](https://github.com/yangxiaoge/AndroidExcelReadWrite/blob/master/app/src/main/java/com/yjn/androidexcelreadwrite/ExcelUtil.java), by line 65 in my code , i just getSheetAt(0), but you can get other sheet by index.

**Comment by aryan00018** [comment]
Thanks a lot for replying.....I did changes and it's able to show multiple sheet as I have attached the code what changes I did in ExcelUtil but now the problem  is that it is able to display 2 columns data only but my sheets contains 20 columns so if you may help in this? and one more thing that does it support images present in excel or it supports only text?

` list = new ArrayList<>();
                for (int indexOfSheet = 0; indexOfSheet <= wb.getNumberOfSheets(); indexOfSheet++) {
                    // get the first sheet
                    Sheet sheet = wb.getSheetAt(indexOfSheet);
                    // get the first line header
                    Row rowHeader = sheet.getRow(0);
                    int cellsCount = rowHeader.getPhysicalNumberOfCells();
                    //store header to the map
                    Map<Integer, Object> headerMap = new HashMap<>();
                    for (int c = 0; c < cellsCount; c++) {
                        Object value = getCellFormatValue(rowHeader.getCell(c));
                        String cellInfo = "header " + "; c:" + c + "; v:" + value;
                        Log.i(TAG, "readExcelNew: " + cellInfo);
`

**Comment by yangxiaoge** [comment]
> Thanks a lot for replying.....I did changes and it's able to show multiple sheet as I have attached the code what changes I did in ExcelUtil but now the problem is that it is able to display 2 columns data only but my sheets contains 20 columns so if you may help in this? and one more thing that does it support images present in excel or it supports only text?
> 
> `list = new ArrayList<>(); for (int indexOfSheet = 0; indexOfSheet <= wb.getNumberOfSheets(); indexOfSheet++) { // get the first sheet Sheet sheet = wb.getSheetAt(indexOfSheet); // get the first line header Row rowHeader = sheet.getRow(0); int cellsCount = rowHeader.getPhysicalNumberOfCells(); //store header to the map Map<Integer, Object> headerMap = new HashMap<>(); for (int c = 0; c < cellsCount; c++) { Object value = getCellFormatValue(rowHeader.getCell(c)); String cellInfo = "header " + "; c:" + c + "; v:" + value; Log.i(TAG, "readExcelNew: " + cellInfo);`

the first question: `row.getPhysicalNumberOfCells()` can show you the count of columns current sheet, so it was dynamic. second: i just know this excel support `boolean`, `number`, `string`.
