### ISSUE TITLE
I can't build app.

### ISSUE THREAD

**Issue by liuyi73191** [yangxiaoge/AndroidExcelReadWrite#2]
Hi, I can't build app because of BaseVIewHolder. I will add screenshot.
![2021-01-22_004643](https://user-images.githubusercontent.com/73023998/105382985-9ceccf80-5c4b-11eb-834b-621e303e0c8b.png)

**Comment by liuyi73191** [comment]
Please help me

**Comment by CN-Shopkeeper** [comment]
go check your build.gradle(app) dependencies:
```gradle
dependencies {
    // ...
    // BaseRecyclerViewAdapterHelper
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.47'
}
```
